core:
  - changed-files:
      - any-glob-to-any-file: ['src/*.rs']

renderer:
  - changed-files:
      - any-glob-to-any-file: ['src/renderers/**/*.rs']

vulkan:
  - changed-files:
    - any-glob-to-any-file: ['src/renderers/*vulkan*.rs', 'src/renderers/vulkan/**/*.rs']

directx:
  - changed-files:
    - any-glob-to-any-file: ['src/renderers/*directx*.rs', 'src/renderers/directx/**/*.rs']

metal:
  - changed-files:
    - any-glob-to-any-file: ['src/renderers/*metal*.rs', 'src/renderers/metal/**/*.rs']

opengl:
  - changed-files:
    - any-glob-to-any-file: ['src/renderers/*opengl*.rs', 'src/renderers/opengl/**/*.rs']

shader:
  - changed-files:
    - any-glob-to-any-file: ['**/*.glsl', '**/*.hlsl', '**/*.vert', '**/*.frag', '**/*.comp', '**/*.spv']

script:
  - changed-files:
    - any-glob-to-any-file: ['**/*.py']

test:
  - changed-files:
    - any-glob-to-any-file: ['tests/**/*.rs', '**/*.glsl', '**/*.hlsl', '**/*.vert', '**/*.frag', '**/*.comp', '**/*.spv']

example:
  - changed-files:
    - any-glob-to-any-file: ['examples/**/*.rs', '**/*.glsl', '**/*.hlsl', '**/*.vert', '**/*.frag', '**/*.comp', '**/*.spv']

infrastructure:
  - changed-files:
      - any-glob-to-any-file: ['.github/**', '**/*.toml']

documentation:
  - changed-files:
      - any-glob-to-any-file: ['**/*.md']
