[package]
name = "heph-gl"
version = "0.1.0"
edition = "2024"

[dependencies]
renkrs = "0.1.0"
glam = "0.33.2"
raw-window-handle = "0.6.2"
ash = "0.38.0"
ash-window = "0.13.0"
vk-mem = "0.5.0"

[dev-dependencies]
bytemuck = "1.25.0"
winit = "0.30.13"
libtest-mimic = "0.7"

[features]
default = ["vulkan"]
vulkan = []
directx = []
metal = []
opengl = []

[[test]]
name = "vulkan"
harness = false

[lints.rust]
unreachable_patterns = "deny"
unused_variables = "deny"
unused_imports = "deny"
unused_macros = "deny"
unconditional_recursion = "deny"
overflowing_literals = "deny"
dead_code = "warn"

while_true = "deny"

non_camel_case_types = "deny"
non_snake_case = "deny"
non_upper_case_globals = "deny"
