name: Examples

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  examples:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          cache: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0

      - name: Run Examples (Linux)
        if: runner.os == 'Linux'
        run: |
          for file in examples/*.rs; do
            xvfb-run -a cargo run --example "$(basename "$file" .rs)"
          done

      - name: Run Examples (Windows)
        if: runner.os == 'Windows'
        shell: bash
        run: |
          for file in examples/*.rs; do
            cargo run --example "$(basename "$file" .rs)"
          done

      - name: Run Examples (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          export VK_ICD_FILENAMES="$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json"
          for file in examples/*.rs; do
            cargo run --example "$(basename "$file" .rs)"
          done
