name: Examples

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_call:

jobs:
  examples:
    name: Run Examples (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Environment
        uses: ./.github/actions/setup-env
        with:
          nextest: true

      - name: Run Examples
        shell: bash
        run: |
          for file in examples/*.rs; do
            $HEPHGL_NEXTEST_PREFIX cargo run --example "$(basename "$file" .rs)"
          done
