name: Pre Commit

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_call:

jobs:
  prek:
    name: Run prek
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Nightly
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      - name: Install Clippy
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Cache Rust env
        uses: Swatinem/rust-cache@v2

      - name: Install prek
        run: cargo install --locked prek

      - name: Run prek 
        run: prek run --all-files
