name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libvulkan1 mesa-vulkan-drivers vulkan-tools

      - name: Run Nextest (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run cargo nextest run

      - name: Run Nextest (Windows & macOS)
        if: runner.os != 'Linux'
        run: cargo nextest run
