name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_call:

jobs:
  unit-tests:
    name: Run Unit Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Run
        run: cargo test

  integration-tests:
    name: Run Integration Tests (${{ matrix.os }})
    needs: unit-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          cache: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0

      - name: Run (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run cargo nextest run

      - name: Run (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo nextest run

      - name: Run (macOS)
        if: runner.os == 'macOS'
        run: |
          export VK_ICD_FILENAMES="$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json"
          cargo nextest run

  coverage:
    name: Code Coverage (${{ matrix.os }})
    needs: integration-tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          cache: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0

      - name: Run Unit Tests Coverage
        run: cargo llvm-cov --no-report --lib

      - name: Run Integration Tests Coverage (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run cargo llvm-cov nextest --no-report

      - name: Run Integration Tests Coverage (Windows)
        if: runner.os == 'Windows'
        run: cargo llvm-cov nextest --no-report

      - name: Run Integration Tests Coverage (macOS)
        if: runner.os == 'macOS'
        run: |
          export VK_ICD_FILENAMES="$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json"
          cargo llvm-cov nextest --no-report

      - name: Generate Report
        run: cargo llvm-cov report --cobertura --output-path coverage-${{ matrix.os }}.xml --fail-under-lines 80

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ matrix.os }}
          path: coverage-${{ matrix.os }}.xml
