name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_call:

jobs:
  test:
    name: Run Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}

      - name: Install cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Install Vulkan SDK
        uses: jakoch/install-vulkan-sdk-action@v1.6.0
        with:
          cache: true
          install_swiftshader: true
          install_lavapipe: true

      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0

      - name: Run Nextest (Linux)
        if: runner.os == 'Linux'
        run: xvfb-run cargo nextest run

      - name: Run Nextest (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo nextest run

      - name: Run Nextest (macOS)
        if: runner.os == 'macOS'
        run: |
          export VK_ICD_FILENAMES="$VULKAN_SDK/share/vulkan/icd.d/MoltenVK_icd.json"
          cargo nextest run
